project_name: 'kubectl-openebs'

before:
  hooks:
    - go mod tidy
#    - go generate ./...

builds:
  # TODO: Need to change according to the refactor
  - main: './kubectl-openebs.go'
    env:
      - CGO_ENABLED=0
    goos: ['linux', 'darwin', 'windows']
    goarch: ['386', 'amd64', 'arm64']
    ldflags:
      - "-X 'github.com/openebs/openebsctl/cmd.Version={{ .Tag }}'"

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', '^test:', 'Merge pull request', 'Merge branch']

archives:
  - name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ title .Os }}_{{ if eq .Arch "386" }}x86_32{{ else if eq .Arch "amd64"}}x86_64{{ else }}{{ .Arch }}{{ end }}'
    format_overrides:
      - goos: 'windows'
        format: 'zip'

    wrap_in_directory: false
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums_{{ .Tag }}.txt'
  algorithm: sha256

release:
  name_template: "{{.ProjectName}}-{{.Tag}}"
  header: '# Welcome to this new release!'
  footer: '<img src="https://avatars.githubusercontent.com/u/20769039?s=200&v=4" width="35" height="35"/>© 2020-2022 The OpenEBS Authors. All materials licensed under [Apache v2.0](https://www.apache.org/licenses/LICENSE-2.0.html)'

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ title .Os }}_{{ if eq .Arch "386" }}x86_32{{ else if eq .Arch "amd64"}}x86_64{{ else }}{{ .Arch }}{{ end }}'
    vendor: OpenEBS
    homepage: https://openebs.io/
    description: OpenebsCTL is a plugin for kubectl. It allows users to fetch details of their OpenEBS storage components for information and debuggability.
    license: Apache 2.0
    formats:
      - deb

krews:
- skip_upload: true
  homepage: https://github.com/openebs/openebsctl
  short_description: View and debug OpenEBS storage resources
  description: |
    The openebs plugin provides a simplified interface to view
    and debug different OpenEBS volumes and related storage resources.
  caveats: |
    * This plugin works with newer OpenEBS releases, where volumes are
      provisioned by CSI.
    * For resources that are not in default namespace, you must specify
      -n/--namespace explicitly (the current namespace setting is not
      yet used).