apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: openebs
spec:
  version: {{ .TagName }}
  homepage: https://github.com/openebs/openebsctl
  shortDescription: View and debug OpenEBS storage resources
  description: |
    The openebs plugin provides a simplified interface to view
    and debug different OpenEBS volumes and related storage resources.
  caveats: |
    * This plugin works with newer OpenEBS releases, where volumes are
      provisioned by CSI.
    * For resources that are not in default namespace, you must specify
      -n/--namespace explicitly (the current namespace setting is not
      yet used).
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/openebs/openebsctl/releases/download/{{ .TagName }}/kubectl-openebs_{{ .TagName }}_Darwin_x86_64.tar.gz" .TagName }}
      bin: kubectl-openebs
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/openebs/openebsctl/releases/download/{{ .TagName }}/kubectl-openebs_{{ .TagName }}_Darwin_arm64.tar.gz" .TagName }}
      bin: kubectl-openebs
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/openebs/openebsctl/releases/download/{{ .TagName }}/kubectl-openebs_{{ .TagName }}_Linux_x86_64.tar.gz" .TagName }}
      bin: kubectl-openebs
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/openebs/openebsctl/releases/download/{{ .TagName }}/kubectl-openebs_{{ .TagName }}_Linux_arm64.tar.gz" .TagName }}
      bin: kubectl-openebs
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/openebs/openebsctl/releases/download/{{ .TagName }}/kubectl-openebs_{{ .TagName }}_Windows_x86_64.zip" .TagName }}
      bin: kubectl-openebs.exe
