name: Release Binary

on:
  release:
    types:
      - "created"
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.9
          cache: false
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --release-notes=CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GR_TOKEN }}
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.46
        with:
          krew_template_file: scripts/openebs.yaml
