name: tests and coverage
on:
  push:
    tags:
      - v*
    branches:
      - develop
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Run coverage
        run: go test ./... --coverprofile=coverage.out --covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
