name: tests and coverage
on:
  push:
    tags:
      - v*
    branches:
      - develop
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.9
          cache: false
      - name: Run coverage
        run: go test ./... --coverprofile=coverage.out --covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
